language: cpp

sudo: required

services:
    - docker

script:
    - docker run -v ${TRAVIS_BUILD_DIR}:/root/src/ -w /root/src/ $DOCKER_IMAGE /bin/bash .travis-build.sh $DOCKER_IMAGE

env:
    - DOCKER_IMAGE=centos:7
    - DOCKER_IMAGE=fedora:27
    - DOCKER_IMAGE=fedora:26

before_deploy:
    - openssl aes-256-cbc -K $encrypted_2e8b57d1cb90_key -iv $encrypted_2e8b57d1cb90_iv -in .copr.enc -out .copr -d

deploy:
    skip_cleanup: true
    provider: script
    script: docker run -v ${TRAVIS_BUILD_DIR}:/root/src/ -w /root/src/ fedora:latest /bin/sh -c "dnf install -y copr-cli && copr-cli --config .copr build --nowait pat1/simc libemos.spec"
    on:
        branch: master
        condition: $DOCKER_IMAGE = centos:7
